"""member_user_id

Revision ID: 23371e43a77e
Revises: cb2426768c20
Create Date: 2022-08-27 04:15:03.362690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23371e43a77e'
down_revision = 'cb2426768c20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_member_user_id'), 'member', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_user_id'), table_name='member')
    op.drop_column('member', 'user_id')
    # ### end Alembic commands ###
