"""uuid user added

Revision ID: c62c7986d700
Revises: acc1953fe62c
Create Date: 2022-08-31 11:11:45.323791

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils

# revision identifiers, used by Alembic.
revision = 'c62c7986d700'
down_revision = 'acc1953fe62c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column(
        'user_uuid', fastapi_utils.guid_type.GUID(), nullable=False))
    op.drop_index('ix_member_user_id', table_name='member')
    op.create_index(op.f('ix_member_user_uuid'),
                    'member', ['user_uuid'], unique=True)
    op.drop_column('member', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('user_id', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_member_user_uuid'), table_name='member')
    op.create_index('ix_member_user_id', 'member', ['user_id'], unique=False)
    op.drop_column('member', 'user_uuid')
    # ### end Alembic commands ###
