"""company and members

Revision ID: cb2426768c20
Revises: 
Create Date: 2022-08-26 11:13:15.095967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb2426768c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_iin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('tax_mode', postgresql.ENUM('tax_farm_mode', 'tax_low_too_mode', 'tax_general_mode', 'tax_simplified_mode', name='taxmodesenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_bin_iin'), 'company', ['bin_iin'], unique=True)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    op.create_table('company_members',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('owner', 'analytic', name='membertypesenum'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_members')
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_bin_iin'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
