"""department_catalog

Revision ID: d2899ba7bb50
Revises: 23371e43a77e
Create Date: 2022-08-27 07:55:31.803680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2899ba7bb50'
down_revision = '23371e43a77e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=1000), nullable=True),
    sa.Column('name_kz', sa.String(length=1000), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('code_hatch', sa.String(length=100), nullable=True),
    sa.Column('name_ru', sa.String(length=1000), nullable=True),
    sa.Column('name_kz', sa.String(length=1000), nullable=True),
    sa.Column('pay_nds', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_id'), 'catalog', ['id'], unique=False)
    op.add_column('company', sa.Column('pay_nds', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('seria_nds', sa.String(length=100), nullable=True))
    op.add_column('company', sa.Column('number_nds', sa.String(length=100), nullable=True))
    ndstypesenum = postgresql.ENUM('nds_inside', 'nds_outside', name='ndstypesenum')
    ndstypesenum.create(op.get_bind(), checkfirst=True)
    op.add_column('company', sa.Column('nds_type', ndstypesenum, nullable=True))
    op.add_column('company', sa.Column('pin_prog', sa.String(length=100), nullable=True))
    op.add_column('company', sa.Column('pin_kassa_in', sa.String(length=100), nullable=True))
    op.add_column('company', sa.Column('pin_close_shift', sa.String(length=100), nullable=True))
    op.add_column('company', sa.Column('pin_rmni', sa.String(length=100), nullable=True))
    op.add_column('company', sa.Column('filled_fields', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'created_at')
    op.drop_column('company', 'filled_fields')
    op.drop_column('company', 'pin_rmni')
    op.drop_column('company', 'pin_close_shift')
    op.drop_column('company', 'pin_kassa_in')
    op.drop_column('company', 'pin_prog')
    op.drop_column('company', 'nds_type')
    op.drop_column('company', 'number_nds')
    op.drop_column('company', 'seria_nds')
    op.drop_column('company', 'pay_nds')
    op.drop_index(op.f('ix_catalog_id'), table_name='catalog')
    op.drop_table('catalog')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
